"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { saveWalkthroughSummary } from "@/lib/actions/walkthroughs";
import { createClient } from "@/lib/supabase/client";
import {
  Sparkles,
  Save,
  Loader2,
  FileDown,
  Pencil,
  Download,
} from "lucide-react";
import type { WalkthroughNote, WalkthroughFile } from "@/types/database";

interface WalkthroughReviewPanelProps {
  walkthroughId: string;
  summary: string | null;
  notes: WalkthroughNote[];
  files: WalkthroughFile[];
  walkthroughName?: string;
  address?: string | null;
  visitDate: string;
  purpose?: string | null;
  reportMode?: boolean;
}

export function WalkthroughReviewPanel({
  walkthroughId,
  summary: initialSummary,
  notes,
  files,
  walkthroughName,
  address,
  visitDate,
  purpose,
  reportMode = false,
}: WalkthroughReviewPanelProps) {
  const [summary, setSummary] = useState(initialSummary ?? "");
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [editing, setEditing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [exporting, setExporting] = useState(false);
  const [downloadingAll, setDownloadingAll] = useState(false);

  // Photo selection — all selected by default
  const [selectedIds, setSelectedIds] = useState<Set<string>>(
    () => new Set(files.map((f) => f.id))
  );

  // Signed URLs cache
  const [signedUrls, setSignedUrls] = useState<Record<string, string>>({});
  const urlsFetched = useRef(false);

  useEffect(() => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      for (const f of files) {
        if (!next.has(f.id)) next.add(f.id);
      }
      for (const id of next) {
        if (!files.find((f) => f.id === id)) next.delete(id);
      }
      return next;
    });
  }, [files]);

  useEffect(() => {
    if (files.length === 0 || urlsFetched.current) return;
    urlsFetched.current = true;

    const supabase = createClient();
    Promise.all(
      files.map(async (f) => {
        const { data } = await supabase.storage
          .from("project-files")
          .createSignedUrl(f.storage_path, 3600);
        return [f.id, data?.signedUrl ?? ""] as const;
      })
    ).then((entries) => {
      setSignedUrls(Object.fromEntries(entries));
    });
  }, [files]);

  // Auto-generate summary when Review tab opens and no summary exists
  const autoGenerated = useRef(false);
  useEffect(() => {
    if (
      !reportMode &&
      !autoGenerated.current &&
      !summary &&
      notes.length > 0 &&
      !generating
    ) {
      autoGenerated.current = true;
      handleGenerate();
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  function togglePhoto(id: string) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }

  async function handleGenerate() {
    if (notes.length === 0) {
      setError("Add some notes before generating a summary.");
      return;
    }

    setGenerating(true);
    setError(null);

    try {
      const res = await fetch("/api/generate-site-visit-summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          notes: notes.map((n) => ({ content: n.content, source: n.source })),
          projectName: walkthroughName,
          address,
          purpose,
          summaryType: "pricing",
          fileUrls: [],
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error ?? "Failed to generate summary");
      } else {
        setSummary(data.summary);
        await saveWalkthroughSummary(walkthroughId, data.summary);
      }
    } catch {
      setError("Failed to generate summary. Please try again.");
    }

    setGenerating(false);
  }

  async function handleSave() {
    setSaving(true);
    const result = await saveWalkthroughSummary(walkthroughId, summary);
    setSaving(false);

    if (result.error) {
      setError(result.error);
    } else {
      setEditing(false);
    }
  }

  const handleExportPdf = useCallback(async () => {
    setExporting(true);

    const orange = { r: 234, g: 88, b: 12 };
    const darkBg = { r: 28, g: 25, b: 23 };
    const warmGray = { r: 120, g: 113, b: 108 };
    const lightLine = { r: 214, g: 211, b: 209 };

    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 18;
      const contentWidth = pageWidth - margin * 2;
      let y = 0;

      let logoData: string | null = null;
      try {
        logoData = await loadImageAsBase64("/logo.jpg");
      } catch { /* continue */ }

      function addFirstPageHeader() {
        const bannerH = 30;
        doc.setFillColor(255, 255, 255);
        doc.rect(0, 0, pageWidth, bannerH, "F");
        const darkStartX = 62;
        doc.setFillColor(darkBg.r, darkBg.g, darkBg.b);
        doc.rect(darkStartX, 0, pageWidth - darkStartX, bannerH, "F");
        doc.setFillColor(darkBg.r, darkBg.g, darkBg.b);
        doc.triangle(darkStartX - 12, 0, darkStartX, 0, darkStartX, bannerH, "F");
        doc.setFillColor(orange.r, orange.g, orange.b);
        doc.rect(0, bannerH, pageWidth, 1.5, "F");
        if (logoData) {
          const logoH = 24;
          const logoW = logoH * 1.65;
          const logoY = (bannerH - logoH) / 2;
          doc.addImage(logoData, "JPEG", 6, logoY, logoW, logoH);
        }
        doc.setFont("helvetica", "bold");
        doc.setFontSize(11);
        doc.setTextColor(orange.r, orange.g, orange.b);
        doc.text("WALKTHROUGH REPORT", pageWidth - margin, 13, { align: "right" });
        const genDate = new Date().toLocaleDateString("en-US", {
          month: "long", day: "numeric", year: "numeric",
        });
        doc.setFont("helvetica", "normal");
        doc.setFontSize(8);
        doc.setTextColor(200, 200, 200);
        doc.text(genDate, pageWidth - margin, 20, { align: "right" });
      }

      function sectionHeading(title: string, atY: number): number {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(12);
        doc.setTextColor(darkBg.r, darkBg.g, darkBg.b);
        doc.text(title, margin, atY + 5);
        doc.setDrawColor(orange.r, orange.g, orange.b);
        doc.setLineWidth(0.5);
        doc.line(margin, atY + 7, margin + doc.getTextWidth(title), atY + 7);
        return atY + 13;
      }

      function thinDivider(atY: number): number {
        doc.setDrawColor(lightLine.r, lightLine.g, lightLine.b);
        doc.setLineWidth(0.3);
        doc.line(margin, atY, pageWidth - margin, atY);
        return atY + 5;
      }

      function ensureSpace(needed: number) {
        if (y + needed > pageHeight - 22) {
          doc.addPage();
          y = margin;
        }
      }

      addFirstPageHeader();
      y = 38;

      const infoX = margin + 5;
      const labelW = 22;

      let rowCount = 1;
      rowCount++;
      if (address) rowCount++;
      if (purpose) rowCount++;

      const infoBoxHeight = 10 + rowCount * 5.5;

      doc.setFillColor(250, 248, 246);
      doc.setDrawColor(lightLine.r, lightLine.g, lightLine.b);
      doc.setLineWidth(0.3);
      doc.roundedRect(margin, y, contentWidth, infoBoxHeight, 2, 2, "FD");
      doc.setFillColor(orange.r, orange.g, orange.b);
      doc.rect(margin, y, 1.5, infoBoxHeight, "F");

      let infoY = y + 7;

      if (walkthroughName) {
        doc.setFont("helvetica", "bold");
        doc.setFontSize(13);
        doc.setTextColor(darkBg.r, darkBg.g, darkBg.b);
        doc.text(walkthroughName, infoX, infoY);
        infoY += 7;
      }

      doc.setFontSize(9);
      const labelColor = () => doc.setTextColor(orange.r, orange.g, orange.b);
      const valueColor = () => doc.setTextColor(80, 77, 74);

      function infoRow(label: string, value: string) {
        labelColor();
        doc.setFont("helvetica", "bold");
        doc.text(label, infoX, infoY);
        valueColor();
        doc.setFont("helvetica", "normal");
        doc.text(value, infoX + labelW, infoY);
        infoY += 5.5;
      }

      const dateStr = new Date(visitDate).toLocaleDateString("en-US", {
        weekday: "long", month: "long", day: "numeric", year: "numeric",
      });
      infoRow("DATE", dateStr);
      if (address) infoRow("ADDRESS", address);
      if (purpose) infoRow("PURPOSE", purpose);

      y += infoBoxHeight + 8;

      if (summary) {
        y = sectionHeading("Summary", y);
        const summaryLines = summary.split("\n");
        for (const rawLine of summaryLines) {
          const trimmed = rawLine.trim();
          if (!trimmed) { y += 3; continue; }
          if (trimmed.startsWith("## ") || trimmed.startsWith("# ")) {
            ensureSpace(10);
            y += 2;
            const headingText = trimmed.replace(/^#+\s*/, "");
            doc.setFont("helvetica", "bold");
            doc.setFontSize(10.5);
            doc.setTextColor(darkBg.r, darkBg.g, darkBg.b);
            doc.text(headingText, margin, y);
            y += 6;
            continue;
          }
          let text = trimmed;
          const isBullet = /^[-*]\s/.test(text) || /^-\s\[.\]\s/.test(text);
          text = text.replace(/^[-*]\s(\[.\]\s)?/, "");
          text = text.replace(/\*\*(.*?)\*\*/g, "$1");
          text = text.replace(/\*(.*?)\*/g, "$1");
          const indent = isBullet ? margin + 4 : margin;
          const lineWidth = isBullet ? contentWidth - 4 : contentWidth;
          doc.setFont("helvetica", "normal");
          doc.setFontSize(10);
          doc.setTextColor(60, 57, 53);
          const wrapped = doc.splitTextToSize(text, lineWidth);
          for (let wi = 0; wi < wrapped.length; wi++) {
            ensureSpace(6);
            if (isBullet && wi === 0) {
              doc.setFillColor(orange.r, orange.g, orange.b);
              doc.circle(margin + 1.5, y - 1.2, 0.8, "F");
            }
            doc.setTextColor(60, 57, 53);
            doc.text(wrapped[wi], indent, y);
            y += 5;
          }
        }
        y += 6;
        y = thinDivider(y);
      }

      const selectedFiles = files.filter((f) => selectedIds.has(f.id));
      if (selectedFiles.length > 0) {
        ensureSpace(30);
        y = sectionHeading(`Photos  (${selectedFiles.length})`, y);
        const gap = 5;
        const imgWidth = (contentWidth - gap) / 2;
        const imgHeight = imgWidth * 0.75;
        for (let i = 0; i < selectedFiles.length; i += 2) {
          ensureSpace(imgHeight + 8);
          const drawPhotoCard = async (fileId: string, x: number) => {
            const url = signedUrls[fileId];
            if (!url) return;
            try {
              doc.setFillColor(230, 228, 226);
              doc.roundedRect(x + 0.5, y + 0.5, imgWidth, imgHeight, 1.5, 1.5, "F");
              doc.setFillColor(255, 255, 255);
              doc.roundedRect(x, y, imgWidth, imgHeight, 1.5, 1.5, "F");
              const imgData = await loadImageAsBase64(url);
              doc.addImage(imgData, "JPEG", x + 1, y + 1, imgWidth - 2, imgHeight - 2);
            } catch { /* skip */ }
          };
          await drawPhotoCard(selectedFiles[i].id, margin);
          if (i + 1 < selectedFiles.length) {
            await drawPhotoCard(selectedFiles[i + 1].id, margin + imgWidth + gap);
          }
          y += imgHeight + 5;
        }
      }

      const totalPages = doc.getNumberOfPages();
      for (let p = 1; p <= totalPages; p++) {
        doc.setPage(p);
        doc.setFillColor(orange.r, orange.g, orange.b);
        doc.rect(0, pageHeight - 12, pageWidth, 0.5, "F");
        doc.setFontSize(7);
        doc.setFont("helvetica", "normal");
        doc.setTextColor(warmGray.r, warmGray.g, warmGray.b);
        doc.text("Penney Construction  ·  Walkthrough Report", margin, pageHeight - 6);
        doc.text(`Page ${p} of ${totalPages}`, pageWidth - margin, pageHeight - 6, { align: "right" });
      }

      const filename = `walkthrough-${(walkthroughName ?? "report").replace(/\s+/g, "-").toLowerCase()}-${new Date(visitDate).toISOString().slice(0, 10)}.pdf`;
      doc.save(filename);
    } catch (err) {
      console.error("PDF export failed:", err);
      setError("Failed to export PDF. Please try again.");
    }

    setExporting(false);
  }, [summary, files, selectedIds, signedUrls, walkthroughName, address, visitDate, purpose]);

  async function handleDownloadAll() {
    setDownloadingAll(true);
    try {
      const selectedFiles = files.filter((f) => selectedIds.has(f.id));
      for (let i = 0; i < selectedFiles.length; i++) {
        const file = selectedFiles[i];
        const url = signedUrls[file.id];
        if (!url) continue;
        const response = await fetch(url);
        const blob = await response.blob();
        const blobUrl = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = blobUrl;
        a.download = file.file_name;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(blobUrl);
        if (i < selectedFiles.length - 1) {
          await new Promise((r) => setTimeout(r, 500));
        }
      }
    } finally {
      setDownloadingAll(false);
    }
  }

  if (reportMode) {
    return (
      <div className="space-y-4">
        {summary ? (
          <Card>
            <CardContent className="py-4">
              <h3 className="text-sm font-semibold mb-2">Summary</h3>
              <p className="text-sm whitespace-pre-wrap text-muted-foreground">{summary}</p>
            </CardContent>
          </Card>
        ) : (
          <p className="text-center text-sm text-muted-foreground py-8">
            No summary yet. Go to the Review tab to generate one.
          </p>
        )}
        {files.length > 0 && (
          <p className="text-xs text-muted-foreground text-center">
            {selectedIds.size} of {files.length} photos selected for export
          </p>
        )}
        {error && <p className="text-sm text-destructive">{error}</p>}
        <Button
          className="w-full h-12 text-base"
          disabled={exporting || (!summary && files.length === 0)}
          onClick={handleExportPdf}
        >
          {exporting ? (
            <>
              <Loader2 className="mr-2 h-5 w-5 animate-spin" />
              Generating PDF...
            </>
          ) : (
            <>
              <FileDown className="mr-2 h-5 w-5" />
              Export PDF
            </>
          )}
        </Button>
      </div>
    );
  }

  return (
    <div className="space-y-4">
      {files.length > 0 && (
        <div>
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm font-medium">
              Photos ({selectedIds.size}/{files.length} selected)
            </p>
            <Button
              variant="ghost"
              size="sm"
              className="text-xs h-7"
              onClick={() => {
                if (selectedIds.size === files.length) {
                  setSelectedIds(new Set());
                } else {
                  setSelectedIds(new Set(files.map((f) => f.id)));
                }
              }}
            >
              {selectedIds.size === files.length ? "Deselect All" : "Select All"}
            </Button>
          </div>
          <div className="grid grid-cols-2 gap-2">
            {files.map((file) => {
              const isSelected = selectedIds.has(file.id);
              return (
                <div
                  key={file.id}
                  className={`relative rounded-lg overflow-hidden bg-muted cursor-pointer ring-2 transition-all ${
                    isSelected ? "ring-primary" : "ring-transparent"
                  }`}
                  onClick={() => togglePhoto(file.id)}
                >
                  <div className="aspect-[4/3] relative">
                    {signedUrls[file.id] ? (
                      <Image
                        src={signedUrls[file.id]}
                        alt={file.file_name}
                        fill
                        loading="lazy"
                        className={`object-cover transition-opacity ${isSelected ? "" : "opacity-40"}`}
                        sizes="(max-width: 640px) 50vw, 25vw"
                      />
                    ) : (
                      <div className="flex items-center justify-center h-full">
                        <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                      </div>
                    )}
                  </div>
                  <div className="absolute top-2 left-2">
                    <Checkbox
                      checked={isSelected}
                      onCheckedChange={() => togglePhoto(file.id)}
                      className="h-6 w-6 border-2 border-white bg-black/40 data-[state=checked]:bg-primary data-[state=checked]:border-primary rounded"
                      onClick={(e) => e.stopPropagation()}
                    />
                  </div>
                </div>
              );
            })}
          </div>
          <Button
            type="button"
            variant="outline"
            className="w-full mt-3"
            disabled={downloadingAll || selectedIds.size === 0}
            onClick={handleDownloadAll}
          >
            {downloadingAll ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Downloading...
              </>
            ) : (
              <>
                <Download className="mr-2 h-4 w-4" />
                Download {selectedIds.size} Photo{selectedIds.size !== 1 ? "s" : ""}
              </>
            )}
          </Button>
        </div>
      )}

      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-sm font-semibold">Summary</h3>
          {summary && !editing && (
            <Button variant="ghost" size="sm" className="text-xs h-7" onClick={() => setEditing(true)}>
              <Pencil className="mr-1 h-3 w-3" />
              Edit
            </Button>
          )}
        </div>

        {generating && (
          <div className="flex items-center gap-2 py-6 justify-center text-muted-foreground">
            <Loader2 className="h-5 w-5 animate-spin" />
            <span className="text-sm">Generating summary...</span>
          </div>
        )}

        {!generating && !summary && (
          <div className="space-y-3">
            <p className="text-sm text-muted-foreground text-center py-4">
              {notes.length === 0
                ? "Add notes in the Capture tab first, then generate a summary."
                : "Ready to generate a walkthrough summary."}
            </p>
            <Button className="w-full" disabled={notes.length === 0} onClick={() => handleGenerate()}>
              <Sparkles className="mr-2 h-4 w-4" />
              Generate AI Summary
            </Button>
          </div>
        )}

        {!generating && summary && editing && (
          <div className="space-y-2">
            <Textarea value={summary} onChange={(e) => setSummary(e.target.value)} rows={12} className="font-mono text-sm" />
            <div className="flex gap-2">
              <Button variant="outline" className="flex-1" onClick={() => { setSummary(initialSummary ?? ""); setEditing(false); }}>
                Cancel
              </Button>
              <Button className="flex-1" disabled={saving} onClick={handleSave}>
                {saving ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Save className="mr-2 h-4 w-4" />}
                Save
              </Button>
            </div>
          </div>
        )}

        {!generating && summary && !editing && (
          <Card>
            <CardContent className="py-3">
              <p className="text-sm whitespace-pre-wrap">{summary}</p>
            </CardContent>
          </Card>
        )}

        {!generating && summary && (
          <Button variant="ghost" size="sm" className="w-full mt-2 text-muted-foreground" disabled={notes.length === 0} onClick={() => handleGenerate()}>
            <Sparkles className="mr-1 h-3.5 w-3.5" />
            Regenerate Summary
          </Button>
        )}
      </div>

      {error && <p className="text-sm text-destructive">{error}</p>}

      <Button
        className="w-full h-12 text-base"
        disabled={exporting || (!summary && files.length === 0)}
        onClick={handleExportPdf}
      >
        {exporting ? (
          <>
            <Loader2 className="mr-2 h-5 w-5 animate-spin" />
            Generating PDF...
          </>
        ) : (
          <>
            <FileDown className="mr-2 h-5 w-5" />
            Export PDF
          </>
        )}
      </Button>
    </div>
  );
}

async function loadImageAsBase64(url: string): Promise<string> {
  const res = await fetch(url);
  const blob = await res.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}
