"use client";

import { useState, useEffect, useRef, useCallback } from "react";
import Image from "next/image";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Checkbox } from "@/components/ui/checkbox";
import { Textarea } from "@/components/ui/textarea";
import { saveSiteVisitSummary } from "@/lib/actions/site-visits";
import { createClient } from "@/lib/supabase/client";
import {
  Sparkles,
  Save,
  Loader2,
  FileDown,
  Pencil,
  CheckCircle,
} from "lucide-react";
import type { SiteVisitNote, SiteVisitFile } from "@/types/database";

interface SiteVisitReviewPanelProps {
  siteVisitId: string;
  summary: string | null;
  notes: SiteVisitNote[];
  files: SiteVisitFile[];
  projectName?: string;
  projectNumber?: string;
  projectType?: string | null;
  projectStatus?: string | null;
  address?: string | null;
  visitDate: string;
  purpose?: string | null;
  /** When true, shows only the summary + PDF export (Report tab) */
  reportMode?: boolean;
}

export function SiteVisitReviewPanel({
  siteVisitId,
  summary: initialSummary,
  notes,
  files,
  projectName,
  projectNumber,
  projectType,
  projectStatus,
  address,
  visitDate,
  purpose,
  reportMode = false,
}: SiteVisitReviewPanelProps) {
  const [summary, setSummary] = useState(initialSummary ?? "");
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [editing, setEditing] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [exporting, setExporting] = useState(false);

  // Summary type — user picks, default based on project status
  const PRECON_STATUSES = new Set(["lead", "estimating", "proposal_sent"]);
  const defaultType =
    projectStatus && PRECON_STATUSES.has(projectStatus) ? "precon" : "active";
  const [summaryType, setSummaryType] = useState<"precon" | "active">(
    defaultType
  );

  // Photo selection — all selected by default
  const [selectedIds, setSelectedIds] = useState<Set<string>>(
    () => new Set(files.map((f) => f.id))
  );

  // Signed URLs cache
  const [signedUrls, setSignedUrls] = useState<Record<string, string>>({});
  const urlsFetched = useRef(false);

  // Keep selection in sync when files change
  useEffect(() => {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      for (const f of files) {
        if (!next.has(f.id)) next.add(f.id);
      }
      // Remove ids no longer in files
      for (const id of next) {
        if (!files.find((f) => f.id === id)) next.delete(id);
      }
      return next;
    });
  }, [files]);

  // Fetch signed URLs for all files
  useEffect(() => {
    if (files.length === 0 || urlsFetched.current) return;
    urlsFetched.current = true;

    const supabase = createClient();
    Promise.all(
      files.map(async (f) => {
        const { data } = await supabase.storage
          .from("project-files")
          .createSignedUrl(f.storage_path, 3600);
        return [f.id, data?.signedUrl ?? ""] as const;
      })
    ).then((entries) => {
      setSignedUrls(Object.fromEntries(entries));
    });
  }, [files]);

  // Auto-generate summary when Review tab opens and no summary exists
  const autoGenerated = useRef(false);
  useEffect(() => {
    if (
      !reportMode &&
      !autoGenerated.current &&
      !summary &&
      notes.length > 0 &&
      !generating
    ) {
      autoGenerated.current = true;
      handleGenerate();
    }
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  function togglePhoto(id: string) {
    setSelectedIds((prev) => {
      const next = new Set(prev);
      if (next.has(id)) {
        next.delete(id);
      } else {
        next.add(id);
      }
      return next;
    });
  }

  async function handleGenerate(typeOverride?: "precon" | "active") {
    if (notes.length === 0) {
      setError("Add some notes before generating a summary.");
      return;
    }

    const type = typeOverride ?? summaryType;

    setGenerating(true);
    setError(null);

    try {
      const res = await fetch("/api/generate-site-visit-summary", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          notes: notes.map((n) => ({ content: n.content, source: n.source })),
          projectName,
          projectType,
          address,
          purpose,
          summaryType: type,
          fileUrls: [],
        }),
      });

      const data = await res.json();

      if (!res.ok) {
        setError(data.error ?? "Failed to generate summary");
      } else {
        setSummary(data.summary);
        await saveSiteVisitSummary(siteVisitId, data.summary);
      }
    } catch {
      setError("Failed to generate summary. Please try again.");
    }

    setGenerating(false);
  }

  async function handleSave() {
    setSaving(true);
    const result = await saveSiteVisitSummary(siteVisitId, summary);
    setSaving(false);

    if (result.error) {
      setError(result.error);
    } else {
      setEditing(false);
    }
  }

  const handleExportPdf = useCallback(async () => {
    setExporting(true);

    try {
      const { jsPDF } = await import("jspdf");
      const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
      const pageWidth = doc.internal.pageSize.getWidth();
      const pageHeight = doc.internal.pageSize.getHeight();
      const margin = 15;
      const contentWidth = pageWidth - margin * 2;
      let y = margin;

      // ── Header ──
      doc.setFontSize(20);
      doc.setFont("helvetica", "bold");
      doc.text("Site Visit Report", margin, y + 7);
      y += 10;

      doc.setFontSize(10);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(100);
      doc.text("Penney Construction", margin, y + 5);
      y += 10;

      // Divider
      doc.setDrawColor(200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 6;

      // ── Info block ──
      doc.setTextColor(0);
      doc.setFontSize(11);
      doc.setFont("helvetica", "bold");

      if (projectNumber && projectName) {
        doc.text(`${projectNumber} — ${projectName}`, margin, y);
        y += 6;
      }

      doc.setFont("helvetica", "normal");
      doc.setFontSize(10);

      const dateStr = new Date(visitDate).toLocaleDateString("en-US", {
        weekday: "long",
        month: "long",
        day: "numeric",
        year: "numeric",
      });
      doc.text(`Date: ${dateStr}`, margin, y);
      y += 5;

      if (purpose) {
        doc.text(`Purpose: ${purpose}`, margin, y);
        y += 5;
      }
      if (address) {
        doc.text(`Address: ${address}`, margin, y);
        y += 5;
      }

      y += 4;
      doc.setDrawColor(200);
      doc.line(margin, y, pageWidth - margin, y);
      y += 6;

      // ── Summary ──
      if (summary) {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text("Summary", margin, y);
        y += 7;

        doc.setFontSize(10);
        doc.setFont("helvetica", "normal");
        const lines = doc.splitTextToSize(summary, contentWidth);
        for (const line of lines) {
          if (y > pageHeight - 20) {
            doc.addPage();
            y = margin;
          }
          doc.text(line, margin, y);
          y += 5;
        }
        y += 4;
      }

      // ── Photos ──
      const selectedFiles = files.filter((f) => selectedIds.has(f.id));
      if (selectedFiles.length > 0) {
        if (y > pageHeight - 40) {
          doc.addPage();
          y = margin;
        }

        doc.setDrawColor(200);
        doc.line(margin, y, pageWidth - margin, y);
        y += 6;

        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.text(`Photos (${selectedFiles.length})`, margin, y);
        y += 8;

        // Load images
        const imgWidth = (contentWidth - 4) / 2; // 2 columns with gap
        const imgHeight = imgWidth * 0.75; // 4:3 aspect

        for (let i = 0; i < selectedFiles.length; i += 2) {
          if (y + imgHeight > pageHeight - 15) {
            doc.addPage();
            y = margin;
          }

          // Left image
          const leftUrl = signedUrls[selectedFiles[i].id];
          if (leftUrl) {
            try {
              const imgData = await loadImageAsBase64(leftUrl);
              doc.addImage(imgData, "JPEG", margin, y, imgWidth, imgHeight);
            } catch {
              // Skip image if it fails to load
            }
          }

          // Right image
          if (i + 1 < selectedFiles.length) {
            const rightUrl = signedUrls[selectedFiles[i + 1].id];
            if (rightUrl) {
              try {
                const imgData = await loadImageAsBase64(rightUrl);
                doc.addImage(
                  imgData,
                  "JPEG",
                  margin + imgWidth + 4,
                  y,
                  imgWidth,
                  imgHeight
                );
              } catch {
                // Skip image if it fails to load
              }
            }
          }

          y += imgHeight + 4;
        }
      }

      // ── Footer on every page ──
      const totalPages = doc.getNumberOfPages();
      const genDate = new Date().toLocaleDateString("en-US", {
        month: "long",
        day: "numeric",
        year: "numeric",
      });

      for (let p = 1; p <= totalPages; p++) {
        doc.setPage(p);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Generated ${genDate}`, margin, pageHeight - 8);
        doc.text(
          `Page ${p} of ${totalPages}`,
          pageWidth - margin,
          pageHeight - 8,
          { align: "right" }
        );
      }

      const filename = `site-visit-${projectNumber ?? "report"}-${new Date(visitDate).toISOString().slice(0, 10)}.pdf`;
      doc.save(filename);
    } catch (err) {
      console.error("PDF export failed:", err);
      setError("Failed to export PDF. Please try again.");
    }

    setExporting(false);
  }, [
    summary,
    files,
    selectedIds,
    signedUrls,
    projectName,
    projectNumber,
    projectType,
    address,
    visitDate,
    purpose,
  ]);

  // ── Report mode: summary + PDF only ──
  if (reportMode) {
    return (
      <div className="space-y-4">
        {summary ? (
          <Card>
            <CardContent className="py-4">
              <h3 className="text-sm font-semibold mb-2">Summary</h3>
              <p className="text-sm whitespace-pre-wrap text-muted-foreground">
                {summary}
              </p>
            </CardContent>
          </Card>
        ) : (
          <p className="text-center text-sm text-muted-foreground py-8">
            No summary yet. Go to the Review tab to generate one.
          </p>
        )}

        {files.length > 0 && (
          <p className="text-xs text-muted-foreground text-center">
            {selectedIds.size} of {files.length} photos selected for export
          </p>
        )}

        {error && <p className="text-sm text-destructive">{error}</p>}

        <Button
          className="w-full h-12 text-base"
          disabled={exporting || (!summary && files.length === 0)}
          onClick={handleExportPdf}
        >
          {exporting ? (
            <>
              <Loader2 className="mr-2 h-5 w-5 animate-spin" />
              Generating PDF...
            </>
          ) : (
            <>
              <FileDown className="mr-2 h-5 w-5" />
              Export PDF
            </>
          )}
        </Button>
      </div>
    );
  }

  // ── Review mode: photo grid + summary + PDF ──
  return (
    <div className="space-y-4">
      {/* Photo grid with checkboxes */}
      {files.length > 0 && (
        <div>
          <div className="flex items-center justify-between mb-2">
            <p className="text-sm font-medium">
              Photos ({selectedIds.size}/{files.length} selected)
            </p>
            <Button
              variant="ghost"
              size="sm"
              className="text-xs h-7"
              onClick={() => {
                if (selectedIds.size === files.length) {
                  setSelectedIds(new Set());
                } else {
                  setSelectedIds(new Set(files.map((f) => f.id)));
                }
              }}
            >
              {selectedIds.size === files.length
                ? "Deselect All"
                : "Select All"}
            </Button>
          </div>
          <div className="grid grid-cols-2 gap-2">
            {files.map((file) => {
              const isSelected = selectedIds.has(file.id);
              return (
                <div
                  key={file.id}
                  className={`relative rounded-lg overflow-hidden bg-muted cursor-pointer ring-2 transition-all ${
                    isSelected
                      ? "ring-primary"
                      : "ring-transparent"
                  }`}
                  onClick={() => togglePhoto(file.id)}
                >
                  <div className="aspect-[4/3] relative">
                    {signedUrls[file.id] ? (
                      <Image
                        src={signedUrls[file.id]}
                        alt={file.file_name}
                        fill
                        className={`object-cover transition-opacity ${
                          isSelected ? "" : "opacity-40"
                        }`}
                        sizes="(max-width: 640px) 50vw, 25vw"
                      />
                    ) : (
                      <div className="flex items-center justify-center h-full">
                        <Loader2 className="h-5 w-5 animate-spin text-muted-foreground" />
                      </div>
                    )}
                  </div>
                  <div className="absolute top-2 left-2">
                    <Checkbox
                      checked={isSelected}
                      onCheckedChange={() => togglePhoto(file.id)}
                      className="h-6 w-6 border-2 border-white bg-black/40 data-[state=checked]:bg-primary data-[state=checked]:border-primary rounded"
                      onClick={(e) => e.stopPropagation()}
                    />
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Summary section */}
      <div>
        <div className="flex items-center justify-between mb-2">
          <h3 className="text-sm font-semibold">Summary</h3>
          {summary && !editing && (
            <Button
              variant="ghost"
              size="sm"
              className="text-xs h-7"
              onClick={() => setEditing(true)}
            >
              <Pencil className="mr-1 h-3 w-3" />
              Edit
            </Button>
          )}
        </div>

        {generating && (
          <div className="flex items-center gap-2 py-6 justify-center text-muted-foreground">
            <Loader2 className="h-5 w-5 animate-spin" />
            <span className="text-sm">Generating summary...</span>
          </div>
        )}

        {!generating && !summary && (
          <div className="space-y-3">
            <p className="text-sm text-muted-foreground text-center py-4">
              {notes.length === 0
                ? "Add notes in the Capture tab first, then generate a summary."
                : "Pick a summary type, then generate."}
            </p>

            {/* Summary type toggle */}
            <div className="grid grid-cols-2 gap-2">
              <button
                type="button"
                onClick={() => setSummaryType("precon")}
                className={`rounded-lg border-2 p-3 text-left transition-colors ${
                  summaryType === "precon"
                    ? "border-primary bg-primary/5"
                    : "border-muted hover:border-muted-foreground/30"
                }`}
              >
                <span className="text-sm font-medium block">Pricing</span>
                <span className="text-xs text-muted-foreground">
                  Scope, measurements, estimating
                </span>
              </button>
              <button
                type="button"
                onClick={() => setSummaryType("active")}
                className={`rounded-lg border-2 p-3 text-left transition-colors ${
                  summaryType === "active"
                    ? "border-primary bg-primary/5"
                    : "border-muted hover:border-muted-foreground/30"
                }`}
              >
                <span className="text-sm font-medium block">Progress</span>
                <span className="text-xs text-muted-foreground">
                  Work status, issues, next steps
                </span>
              </button>
            </div>

            <Button
              className="w-full"
              disabled={notes.length === 0}
              onClick={() => handleGenerate()}
            >
              <Sparkles className="mr-2 h-4 w-4" />
              Generate AI Summary
            </Button>
          </div>
        )}

        {!generating && summary && editing && (
          <div className="space-y-2">
            <Textarea
              value={summary}
              onChange={(e) => setSummary(e.target.value)}
              rows={12}
              className="font-mono text-sm"
            />
            <div className="flex gap-2">
              <Button
                variant="outline"
                className="flex-1"
                onClick={() => {
                  setSummary(initialSummary ?? "");
                  setEditing(false);
                }}
              >
                Cancel
              </Button>
              <Button className="flex-1" disabled={saving} onClick={handleSave}>
                {saving ? (
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                ) : (
                  <Save className="mr-2 h-4 w-4" />
                )}
                Save
              </Button>
            </div>
          </div>
        )}

        {!generating && summary && !editing && (
          <Card>
            <CardContent className="py-3">
              <p className="text-sm whitespace-pre-wrap">{summary}</p>
            </CardContent>
          </Card>
        )}

        {!generating && summary && (
          <div className="flex gap-2 mt-2">
            <Button
              variant="ghost"
              size="sm"
              className="flex-1 text-muted-foreground"
              disabled={notes.length === 0}
              onClick={() => {
                setSummaryType("precon");
                handleGenerate("precon");
              }}
            >
              <Sparkles className="mr-1 h-3.5 w-3.5" />
              Redo as Pricing
            </Button>
            <Button
              variant="ghost"
              size="sm"
              className="flex-1 text-muted-foreground"
              disabled={notes.length === 0}
              onClick={() => {
                setSummaryType("active");
                handleGenerate("active");
              }}
            >
              <Sparkles className="mr-1 h-3.5 w-3.5" />
              Redo as Progress
            </Button>
          </div>
        )}
      </div>

      {error && <p className="text-sm text-destructive">{error}</p>}

      {/* PDF Export */}
      <Button
        className="w-full h-12 text-base"
        disabled={exporting || (!summary && files.length === 0)}
        onClick={handleExportPdf}
      >
        {exporting ? (
          <>
            <Loader2 className="mr-2 h-5 w-5 animate-spin" />
            Generating PDF...
          </>
        ) : (
          <>
            <FileDown className="mr-2 h-5 w-5" />
            Export PDF
          </>
        )}
      </Button>
    </div>
  );
}

// ── Helper: load image as base64 for jsPDF ──
async function loadImageAsBase64(url: string): Promise<string> {
  const res = await fetch(url);
  const blob = await res.blob();
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(blob);
  });
}
