const {test}=require('node:test');const assert=require('node:assert/strict');
const fs=require('node:fs'),path=require('node:path'),ts=require('typescript');
const cache=new Map();
function load(file){file=path.resolve(file);if(cache.has(file))return cache.get(file).exports;const m={exports:{}};cache.set(file,m);const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;new Function('module','exports','require',code)(m,m.exports,n=>n.startsWith('@/')?load('src/'+n.slice(2)+'.ts'):n.startsWith('.')?load(path.resolve(path.dirname(file),n)+'.ts'):require(n));return m.exports;}
const {roofTriangles,buildingFixtureVisible}=load('src/lib/design/building.ts');
const {defaultRoomSpec}=load('src/types/design.ts');const {parseRoomSpec}=load('src/lib/design/spec-validation.ts');const {computeTakeoff}=load('src/lib/design/takeoff.ts');const {sanitizeSpec}=load('src/lib/design/geometry.ts');
test('roofs have finite closed triangle surfaces at the specified ridge and eaves',()=>{for(const kind of ['gable','hip','shed']){const p=roofTriangles(264,216,84,kind);assert.equal(p.length%9,0);assert.ok(p.every(Number.isFinite));let xs=[],ys=[],zs=[];for(let i=0;i<p.length;i+=3){xs.push(p[i]);ys.push(p[i+1]);zs.push(p[i+2]);}assert.equal(Math.min(...xs),-132);assert.equal(Math.max(...xs),132);assert.equal(Math.min(...ys),0);assert.equal(Math.max(...ys),84);assert.equal(Math.max(...zs),108);}});
test('floor cutaways hide roofs and isolate the selected floor',()=>{const f=l=>({options:{buildingLayer:l}});assert.equal(buildingFixtureVisible(f('roof'),'exterior'),true);assert.equal(buildingFixtureVisible(f('roof'),'first'),false);assert.equal(buildingFixtureVisible(f('upper'),'first'),false);assert.equal(buildingFixtureVisible(f('first'),'upper'),false);assert.equal(buildingFixtureVisible(f('upper'),'upper'),true);});
test('building imports retain model kind and do not report room-box quantities',()=>{const s=defaultRoomSpec();s.modelKind='building';const p=parseRoomSpec(s);assert.equal(p.modelKind,'building');const q=computeTakeoff(p);assert.equal(q.floorAreaSf,0);assert.equal(q.fixtureCounts.length,0);assert.ok(q.warnings[0].includes('whole-house'));assert.ok(computeTakeoff(defaultRoomSpec()).floorAreaSf>0);});
test('Breen model imports without shifting components or losing roofs',{skip: !fs.existsSync('../work/breen-design-r2/Breen-Whole-House-Studio-R4.json')},()=>{const p=parseRoomSpec(JSON.parse(fs.readFileSync('../work/breen-design-r2/Breen-Whole-House-Studio-R4.json','utf8')));const c=sanitizeSpec(p);assert.deepEqual(c.adjusted,[]);assert.ok(p.fixtures.length>500);assert.equal(p.fixtures.filter(f=>f.options?.roofShape).length,7);assert.deepEqual(c.spec.fixtures,p.fixtures);});

