const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const Module = require('node:module');
const path = require('node:path');
const filename = path.resolve('src/lib/design/product-catalog.ts');
const compiled = ts.transpileModule(fs.readFileSync(filename, 'utf8'), { compilerOptions: { module: ts.ModuleKind.CommonJS } }).outputText;
const m = new Module(filename, module); m.filename = filename; m.paths = module.paths; m._compile(compiled, filename);
const { catalogSchema, filterProducts, safeProductUrl, categoryLabel } = m.exports;
const products = JSON.parse(fs.readFileSync(process.argv[2] || '../catalog/bathroom/products.json', 'utf8'));
catalogSchema.parse({ products, updatedAt: new Date().toISOString() });
assert.equal(new Set(products.map(p => p.id)).size, products.length);
assert.equal(filterProducts(products, 'WCG242460DGEWCUNSMXX', 'All', 'name').length, 1);
assert.equal(filterProducts(products, 'green beckett', 'Vanities', 'name').length, 3);
assert.equal(filterProducts(products, 'nonexistent-product-xyz', 'All', 'name').length, 0);
for (const sort of ['price-low', 'price-high']) assert.equal(filterProducts(products, '', 'All', sort).at(-1).unit_price, null);
assert.equal(categoryLabel('toilet seats'), 'Toilets & seats');
assert.equal(safeProductUrl('javascript:alert(1)'), undefined);
assert.equal(safeProductUrl('file:///private'), undefined);
assert.equal(safeProductUrl('https://example.com/spec.pdf'), 'https://example.com/spec.pdf');
console.log(`Catalog validation, model search, multiword/category filters, price sorting and URL safety passed (${products.length} products).`);
